# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
           node-version: '14.x'

      # Runs a single command using the runners shell
      - name: Initialize CI
        run: "echo Initializing CI!"

      # Runs a set of commands using the runners shell
      - name: Run Test
        run: npm test
      - name: Deploy to Heroku
        # You may pin to the exact commit or the version.
        # uses: AkhileshNS/heroku-deploy@dc88b512e1c4626bd70bbac8aa1f1afab5efbd04
        uses: AkhileshNS/heroku-deploy@v3.5.7
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: 2b1511c3-aca0-44d7-bd26-5e6993a44e90
          # Email that you use with heroku
          heroku_email: andyata24.ak@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: github-cicd
          # An optional buildpack to use when creating the heroku application
          #buildpack: # optional
          # The branch that you would like to deploy to Heroku
          # branch: # optional, default is HEAD
          # Set this to true if you don't want to use --force when switching branches
          # dontuseforce: # optional, default is false
          # Will deploy using Dockerfile in project root.
          # usedocker: # optional, default is false
          # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
          # docker_heroku_process_type: # optional, default is web
          # A list of args to pass into the Docker build. This option only makes sense when usedocker enabled
          # docker_build_args: # optional
          # Set if your app is located in a subdirectory.
          # appdir: # optional, default is 
          # A URL to which a healthcheck is performed (checks for 200 request)
          # healthcheck: # optional, default is 
          # Value to check for when conducting healthcheck request
          # checkstring: # optional, default is 
          # Time (in seconds) to wait before performing healthcheck
          # delay: # optional, default is 0
          # Contents of the Procfile to save and deploy
          # procfile: # optional, default is 
          # When set to true this will attempt to rollback to the previous release if the healthcheck fails
          # rollbackonhealthcheckfailed: # optional, default is false
          # Path to an localized env file
          # env_file: # optional, default is 

